Add library pages for boost,gml,trilinos
ARCHER2-HPC/archer2-docs pull request #173
Opened 2021-01-15 17:45 UTC by kevinstratford

Now available as modules

2021-01-17 16:58 UTC, aturner-epcc requested changes
Looks mostly fine. Just a few typos for the service name

2021-01-17 16:58 UTC, aturner-epcc commented on docs/software-libraries/boost.md
> +The Arcer2 github repository contains a recipe for compiling Boost for
Typo, should be ARCHER2

2021-01-17 16:58 UTC, aturner-epcc commented on docs/software-libraries/boost.md
> +Archer2 [github repository][4] for further information.
Typo  should be ARCHER2

2021-01-17 16:58 UTC, aturner-epcc commented on docs/software-libraries/glm.md
> +on Archer2 via the Archer2 github repository:
Typo, should be ARCHER2

2021-01-17 16:58 UTC, aturner-epcc commented on docs/software-libraries/glm.md
> +where the `--prefix` option sets the install location. See the Archer2
Typo, should be ARCHER2

2021-01-17 16:58 UTC, aturner-epcc commented on docs/software-libraries/trilinos.md
> +for Trilinos is available at the Archer2 repository. The script
Typo, should be ARCHER2

2021-01-17 16:58 UTC, aturner-epcc commented on docs/software-libraries/trilinos.md
> +See the Archer2 [github repository][2] for further details.
Typo, should be ARCHER2

2021-01-21 09:36 UTC, kevinstratford commented on docs/software-libraries/boost.md
> +Archer2 [github repository][4] for further information.
Fixed (I hope)

2021-01-25 08:51 UTC, jsindt submitted a review, later dismissed
Typos have been fixed so LGTM

2021-01-26 14:46 UTC, juanfrh approved these changes

2021-01-26 14:46 UTC, merged