Add Dask Jobqueue documentation
ARCHER2-HPC/archer2-docs pull request #369
Opened 2021-12-08 17:52 UTC by holly-t

2021-12-09 10:59 UTC, aturner-epcc requested changes
Thanks @holly-t this looks really useful, just a couple of clarification comments

2021-12-09 10:59 UTC, aturner-epcc commented on docs/user-guide/python.md
> +You can find more information [here](http://jobqueue.dask.org/en/latest/).
Can you change "here" to "in the Dask Job-Queue documentation". The use of "here" for link text is problematic for accessibility reasons.

2021-12-09 10:59 UTC, aturner-epcc commented on docs/user-guide/python.md
> +x = …
Is this an interactive Python script/session that runs on, e.g. the login/data analysis nodes or a script that gets submitted to the queues. I am probably being dense, but was not quite sure. Maybe a sentence clarifying where this runs would be helpful?

2021-12-10 10:17 UTC, holly-t commented
@aturner-epcc I've made the change to the link text and added some further clarification.

2021-12-10 10:53 UTC, aturner-epcc approved these changes
Great thanks @holly-t I will merge this in now

2021-12-10 10:53 UTC, merged