Added initial version of Arm Forge docs
ARCHER2-HPC/archer2-docs pull request #416
Opened 2022-05-31 14:52 UTC by claoidek

2022-05-31 14:54 UTC, kevinstratford commented
Please leave this with me.

2022-06-07 15:11 UTC, kevinstratford submitted a review, later dismissed
I think this is ready to go. I could probably do with someone giving it a go
(particularly if not used `ddt` before).

2022-06-08 09:30 UTC, aturner-epcc requested changes
Looks good - minor change and spotted a typo

2022-06-08 09:30 UTC, aturner-epcc commented on docs/data-tools/arm-forge.md
> +preferred method for many users.
Be a bit stronger here: e.g. "We strongly recommend that users run the remote client on their laptop/desktop.

2022-06-10 13:04 UTC, kevinstratford approved these changes

2022-06-11 08:22 UTC, aturner-epcc requested changes
The images need to be updated to match Arm Forge 22.0.2 - this version has been installed to address a security vulnerability in 21.0.2

2022-06-21 14:41 UTC, aturner-epcc commented
I have updated the documentation text. @claoidek Are you able to update the images of the interface? Once this is done, we should be good to make this live.

2022-06-21 15:28 UTC, claoidek commented
@aturner-epcc Images have now been updated

2022-06-22 07:14 UTC, aturner-epcc requested changes
Thanks @claoidek Just one minor comment - there seems to be a template file missing.

2022-06-22 07:14 UTC, aturner-epcc commented on docs/data-tools/arm-forge.md
> +"Submission template file" enter `${FORGE_ROOT}/templates/archer2.qtf`
This file does not seem to exist?

2022-06-22 08:57 UTC, claoidek commented on docs/data-tools/arm-forge.md
> +"Submission template file" enter `${FORGE_ROOT}/templates/archer2.qtf`
@aturner-epcc This has been rectified

2022-06-22 09:13 UTC, merged