Reservation instructions
ARCHER2-HPC/archer2-docs pull request #640
Opened 2024-10-30 10:43 UTC by kevinstratford

For #639

Could someone check my interpretation is correct?

2024-10-31 10:24 UTC, aturner-epcc requested changes
Looks fine apart from a typo (which predates, this PR I think but it is a good opportunity to fix!)

2024-10-31 10:24 UTC, aturner-epcc commented on docs/user-guide/scheduler.md
> +the scheduler state. To return the estimated start time for a job you spacify the
"spacify" -> "specify"

2024-10-31 10:51 UTC, kevinstratford commented on docs/user-guide/scheduler.md
> +the scheduler state. To return the estimated start time for a job you spacify the
Done.

2024-11-05 08:38 UTC, clairbarrass approved these changes
lgtm

2024-11-05 08:38 UTC, merged